# sudo is required for travis-ci to use ubuntu trusty
# ubuntu trusty is required for libsdl2-dev
sudo: required
dist: trusty

language: c

env:
  global:
    # coverity token
    - secure: "a2pGsG/+LS12sD/vgCF912TKBDDiT8PwRTH50eE94trQoHmD+bubIc4mXR9rSuU/NKNPdn6KZlqrVkVuoIanjYaf+rg28VavGMcBrtVO2cI1yjTUxb5Eq/cT20m3KfZCSFw3iWXfiK1CpDkm9Pdrr2Yz99EGZse3Y6jRGJ6giWM="
  matrix:
    # standard builds
    - CC=gcc
    - CC=clang
    # extra libs
    - CC=gcc USE_CODEC_VORBIS=1 USE_FREETYPE=1
    - CC=clang USE_CODEC_VORBIS=1 USE_FREETYPE=1
    # cross-compile using mingw
    - CC= PLATFORM="mingw32" ARCH="x86"
    - CC= PLATFORM="mingw32" ARCH="x86_64"

script: ./travis-ci-build.sh

notifications:
  email: false

addons:
  apt:
    packages:
      - binutils-mingw-w64-i686
      - gcc-mingw-w64-i686
      - binutils-mingw-w64-x86-64
      - gcc-mingw-w64-x86-64
      - gcc-mingw-w64
      - mingw-w64
      - libgl1-mesa-dev
      - libsdl2-dev
      - libfreetype6-dev
  coverity_scan:
    project:
      name: "ioquake/ioq3"
      description: "Build submitted via Travis CI"
    notification_email: quake3-commits@icculus.org
    build_command_prepend: "make clean"
    build_command: "make release"
    branch_pattern: coverity_scan
