language: c
compiler:
  - gcc
  - clang

script: ./build-test.sh

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -q libgl1-mesa-dev libsdl1.2-dev libvorbis-dev libfreetype6-dev mingw-w64
  
notifications:
  irc: "irc.freenode.org#ioquake3"
